### ISSUE TITLE
grc and ls

### ISSUE THREAD

**Issue by rrosson** [oh-my-fish/plugin-grc#11]
When I have the grc plugin installed and I issue a 'ls' no functions other than the one provided by the plugin:
<code>
function ls
        set -l executable ls
        grc.wrap $executable $argv
end
</code>

my output is a single column with no colors for indicating that it is a file or a directory. Would like to have grc installed and still have the files colored properly and have the choice of either doing columns or not.

**Comment by tannhuber** [comment]
For coloured output you could either

```
set  -U grc_plugin --color
```

or run it manually with

```
ls --color=auto
```

Probably the first is what you prefer.

For the second problem, I cannot see a quick fix. It's a bug/feature of grc.

**Comment by rrosson** [comment]
commit 9af485b worked for me by setting all but ls to use grc.
