### ISSUE TITLE
Something wrong with alias

### ISSUE THREAD

**Issue by taizilongxu** [oh-my-fish/plugin-grc#13]
it will not work with `df` if I have  set `alias df 'df -H'`, so what can I do to make it work?

**Comment by tannhuber** [comment]
Hi,
1. Remove the alias.
2. `set -U grcplugin_df -H`
3. Read the README if you still have trouble :-)
4. Tell me if this can be closed.
5. Merry Christmas!

**Comment by taizilongxu** [comment]
Oh, yes, it works well, thank you very much!!!
