### ISSUE TITLE
please document how to install

### ISSUE THREAD

**Issue by jab** [oh-my-fish/plugin-grc#4]
```
~ λ omf install grc
Trying to clone from URL...
fatal: repository 'grc' does not exist
Could not install package grc.
```

**Comment by bobthecow** [comment]
grc hasn't been updated to work with the new omf (yet). if you want to take a shot at the update, it's fairly straightforward. there are just a bunch of plugins and nobody has gotten around to this one yet :)

**Comment by jab** [comment]
Thanks for the quick response. I'm pretty new to how this works still so I'm not sure how soon I'll be able to help, but I'll give it a whirl if nobody beats me to it. In the meantime, I'm using something like the following in case this helps anyone (based on https://github.com/Homebrew/homebrew/blob/master/Library/Formula/grc.rb#L25-L43):

``` fish
if test $TERM != "dumb"; and available grc
  alias colorify "grc -es --colour auto"
  alias configure 'colorify ./configure'
  alias diff 'colorify diff'
  alias make 'colorify make'
  alias gcc 'colorify gcc'
  alias g++ 'colorify g++'
  alias as 'colorify as'
  alias gas 'colorify gas'
  alias ld 'colorify ld'
  alias netstat 'colorify netstat'
  alias ping 'colorify ping'
  alias traceroute 'colorify /usr/sbin/traceroute'
end
```

**Comment by derekstavis** [comment]
Please test #5, it should fix your issue. Follow this steps:

``` fish
omf cd grc
git fetch origin migrate-structure
git checkout migrate-structure
refresh
```

**Comment by nesl247** [comment]
This can be closed now as the migration-structure branch has been merged in.

**Comment by jab** [comment]
Thanks for getting this working!

**Comment by derekstavis** [comment]
I haven't used this plugin before fixing it, now I see it's awesome having it enabled.

**Comment by jab** [comment]
It seems like you have to either choose between `grc`'s colorization of (uncolorized) `ls` output—which doesn't print directories, symlinks, executables, and non-executable files in different colors—and colorized `ls` output with no `grc`, which doesn't colorize permissions and file sizes for `ls -l`. Am I missing something? Can we have our :fish_cake: and eat it too?

**Comment by nesl247** [comment]
@jab If I think I understand what you are asking, add `set grcplugin_ls --indicator-style=classify --color -xh` to your `config.fish`. This unfortunately will prevent `ls -l` from working until my PR #7 is merged in. You can remove the `-x` from that line until it's merged in, and get very similar output to `ls` as it was before grc, but it will be outputting everything on a new line.

**Comment by jab** [comment]
Oops, I'm on OS X where `/usr/bin/ls` is BSD `ls` not GNU `ls`, so first off I fixed that with `ln -s /usr/local/bin/gls ~/ls`.

Then I noticed `ll --color` does now give both `grc`'s colorization and `ls --color`'s. So after adding `set grcplugin_ls --indicator-style=classify --color -h`, `ll` now gives me what I was looking for.

Thanks @nesl247!
